- name: Pre-configure the environment
  hosts: all
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Configure "sudo" for devops user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/devops
        line: "devops ALL=(ALL) NOPASSWD: ALL"
        state: present
        create: true
        mode: '0644'
        validate: /usr/sbin/visudo -cf %s

    - name: Setup /etc/hosts
      ansible.builtin.template:
        src: "../templates/hosts.j2"
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
